In [1]:
import pandas as pd


In [3]:
df=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people write comment","cricket write comment"],"output":[1,1,0,0]})

In [4]:
print(df)

                    text  output
0   people watch cricket       1
1  cricket watch cricket       1
2   people write comment       0
3  cricket write comment       0


In [9]:
#Document matrix(BOW)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
BOW=CountVectorizer()

In [13]:
document_matrix=BOW.fit_transform(df["text"])#here we convert data into BOW

In [15]:
print(document_matrix)# here we got data as document format so next step is to go with volcublary

  (0, 2)	1
  (0, 3)	1
  (0, 1)	1
  (1, 3)	1
  (1, 1)	2
  (2, 2)	1
  (2, 4)	1
  (2, 0)	1
  (3, 1)	1
  (3, 4)	1
  (3, 0)	1


In [16]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [17]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'cricket': 1, 'write': 4, 'comment': 0}

In [18]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]])

In [19]:
#n-gram range

In [28]:
bigram=CountVectorizer(ngram_range=(3,3))

In [29]:
bigramvocab=bigram.fit_transform(df["text"])

In [30]:
bigram.vocabulary_

{'people watch cricket': 2,
 'cricket watch cricket': 0,
 'people write comment': 3,
 'cricket write comment': 1}

In [31]:
#TF-IDE

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tfide=TfidfVectorizer()

In [38]:
ml=tfide.fit_transform(df["text"]).toarray()

In [39]:
print(ml)

[[0.         0.49681612 0.61366674 0.61366674 0.        ]
 [0.         0.8508161  0.         0.52546357 0.        ]
 [0.57735027 0.         0.57735027 0.         0.57735027]
 [0.61366674 0.49681612 0.         0.         0.61366674]]
